# Generated by Django 4.1.7 on 2023-04-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssage_api', '0005_delete_room_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
    ]
