# Generated by Django 4.1.7 on 2023-04-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssage_api', '0008_conversation_is_seen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
