# Generated by Django 4.1.7 on 2023-04-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssage_api', '0010_gift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='AlternativeLink',
            new_name='alternativeLink',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='GiftName',
            new_name='giftName',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='Link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='Price',
            new_name='price',
        ),
    ]
